.open Database.db
.databases

.headers ON


PRAGMA foreign_keys = OFF;
DROP TABLE IF EXISTS DEPARTMENT;
DROP TABLE IF EXISTS STUDENT;
PRAGMA foreign_keys = ON;

--数据表的建立
CREATE TABLE DEPARTMENT(
	ID INTEGER PRIMARY KEY NOT NULL, -- ID AUTOINCREMENT
	DEPT CHAR(50) NOT NULL,
	UID INT NOT NULL
);
CREATE TABLE STUDENT(
	ID INTEGER PRIMARY KEY NOT NULL,
	DEPARTMENT_ID INTEGER NOT NULL,
	NAME TEXT NOT NULL,
	AGE INT NOT NULL,
	ADDRESS CHAR(50),
	GPA REAL,
	FOREIGN KEY(DEPARTMENT_ID) REFERENCES DEPARTMENT(ID)
);

--插入数据
INSERT INTO DEPARTMENT (ID,DEPT,UID) VALUES (1, '信息科学与技术学院', 20181315);
INSERT INTO DEPARTMENT (ID,DEPT,UID) VALUES (2, '地球科学学院', 20181316);
INSERT INTO DEPARTMENT (ID,DEPT,UID) VALUES (3, '环境与土木工程学院', 20181317);
INSERT INTO DEPARTMENT (ID,DEPT,UID) VALUES (4, '核技术与自动化工程学院', 20181318);
INSERT INTO DEPARTMENT (ID,DEPT,UID) VALUES (5, '材料与化学化工学院', 20181319);
INSERT INTO DEPARTMENT (ID,DEPT,UID) VALUES (6, '管理科学学院', 20181320);

INSERT INTO STUDENT (DEPARTMENT_ID,NAME,AGE,ADDRESS,GPA) VALUES (1, '张三', 32, 'California', 3.9);
INSERT INTO STUDENT (DEPARTMENT_ID,NAME,AGE,ADDRESS,GPA) VALUES (2, '李四', 25, 'Texas', 4.2);
INSERT INTO STUDENT (DEPARTMENT_ID,NAME,AGE,ADDRESS,GPA) VALUES (3, '王五', 23, 'Norway', 3.5);
INSERT INTO STUDENT (DEPARTMENT_ID,NAME,AGE,ADDRESS,GPA) VALUES (4, 'Mark', 25, 'Rich-Mond ', 2.3);
INSERT INTO STUDENT (DEPARTMENT_ID,NAME,AGE,ADDRESS,GPA) VALUES (5, 'David', 27, 'Texas', 4.1);
INSERT INTO STUDENT (DEPARTMENT_ID,NAME,AGE,ADDRESS,GPA) VALUES (6, 'Kim', 22, 'South-Hall', 3.8);


select '******院系表******' AS '';
SELECT * FROM DEPARTMENT;
select '******学生表******' AS '';
SELECT * FROM STUDENT;

select '******学生信息******' AS '';
SELECT STUDENT.NAME,DEPARTMENT.DEPT,STUDENT.GPA,STUDENT.AGE,STUDENT.ADDRESS,DEPARTMENT.UID
FROM STUDENT
INNER JOIN DEPARTMENT on STUDENT.DEPARTMENT_ID = DEPARTMENT.ID;
